# Generated by Django 3.0.4 on 2022-03-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiboapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fibomodel',
            options={'ordering': ['numstr']},
        ),
    ]
