# Generated by Django 3.0.4 on 2021-02-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numstr', models.CharField(max_length=50)),
                ('fact_val', models.CharField(max_length=50)),
            ],
        ),
    ]
